version: '3.3'

services:

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'gc-bridge_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/msql

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080

volumes:
  db-volume:




