version: '3.3'

services:

  database:
    image: mysql:8.0.31 # was 8.0.31 when created
    restart: always
    environment:
      MYSQL_DATABASE: gc-bridge_db
      MYSQL_USER: fbuchner
      MYSQL_PASSWORD: fbuchnerpassword
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Europe/Berlin
    command: ['mysqld', '--default-time-zone=+02:00']
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/msql


  adminer:
    image: adminer:4.8.1 # was 4.8.1 when created
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
      
      
  redis:
    image: redis:7.0-alpine # Lightweight Redis version
    restart: always
    ports:
      - 6379:6379


volumes:
  db-volume:
