version: '3.3'

services:

  database:
    image: mysql:8.0.31 # was 8.0.31 when created
    restart: always
    environment:
      MYSQL_DATABASE: gc-bridge_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/msql

  adminer:
    image: adminer:4.8.1 # was 4.8.1 when created
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080

volumes:
  db-volume:
