"""Url Field in Product

Revision ID: 008c116fddca
Revises: 6db9e5c92f2b
Create Date: 2023-02-21 09:20:40.185713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008c116fddca'
down_revision = '6db9e5c92f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_product_entity', sa.Column('name_url', sa.String(length=255), nullable=True))
    op.drop_column('bridge_product_entity', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_product_entity', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('bridge_product_entity', 'name_url')
    # ### end Alembic commands ###
