"""Order in medias relations

Revision ID: 06e48eeb19ef
Revises: 008c116fddca
Create Date: 2023-03-07 11:04:22.880111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e48eeb19ef'
down_revision = '008c116fddca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_media_cat_entity', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('bridge_media_prod_entity', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_media_prod_entity', 'order')
    op.drop_column('bridge_media_cat_entity', 'order')
    # ### end Alembic commands ###
