"""Add Special dates

Revision ID: 2756d19cd5ab
Revises: 
Create Date: 2023-06-28 08:26:26.665964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2756d19cd5ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_price_entity', sa.Column('special_start_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_price_entity', sa.Column('special_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_price_entity', 'special_end_date')
    op.drop_column('bridge_price_entity', 'special_start_date')
    # ### end Alembic commands ###
