"""shipping and billing address

Revision ID: 2a2333875395
Revises: ec0c02a5a165
Create Date: 2023-06-28 14:46:36.895495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2333875395'
down_revision = 'ec0c02a5a165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_customer_entity', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.add_column('bridge_customer_entity', sa.Column('billing_address_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_bridge_customer_entity_billing_address_id'), 'bridge_customer_entity', ['billing_address_id'])
    op.create_unique_constraint(op.f('uq_bridge_customer_entity_shipping_address_id'), 'bridge_customer_entity', ['shipping_address_id'])
    op.create_foreign_key(op.f('fk_bridge_customer_entity_billing_address_id_bridge_customer_address_entity'), 'bridge_customer_entity', 'bridge_customer_address_entity', ['billing_address_id'], ['id'])
    op.create_foreign_key(op.f('fk_bridge_customer_entity_shipping_address_id_bridge_customer_address_entity'), 'bridge_customer_entity', 'bridge_customer_address_entity', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bridge_customer_entity_shipping_address_id_bridge_customer_address_entity'), 'bridge_customer_entity', type_='foreignkey')
    op.drop_constraint(op.f('fk_bridge_customer_entity_billing_address_id_bridge_customer_address_entity'), 'bridge_customer_entity', type_='foreignkey')
    op.drop_constraint(op.f('uq_bridge_customer_entity_shipping_address_id'), 'bridge_customer_entity', type_='unique')
    op.drop_constraint(op.f('uq_bridge_customer_entity_billing_address_id'), 'bridge_customer_entity', type_='unique')
    op.drop_column('bridge_customer_entity', 'billing_address_id')
    op.drop_column('bridge_customer_entity', 'shipping_address_id')
    # ### end Alembic commands ###
