"""Added Currency

Revision ID: 2b28445495de
Revises: 
Create Date: 2023-01-26 09:19:34.993440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b28445495de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_currency_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ISO', sa.VARCHAR(length=3), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bridge_currency_entity'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridge_currency_entity')
    # ### end Alembic commands ###
