"""Frachtkostenpauschale und Bundle Pauschale

Revision ID: 2ce328640ac0
Revises: 405541a71a5d
Create Date: 2023-03-14 10:47:22.415302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce328640ac0'
down_revision = '405541a71a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_product_entity', sa.Column('shipping_cost_per_bundle', sa.Float(), nullable=True))
    op.add_column('bridge_product_entity', sa.Column('shipping_bundle_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_product_entity', 'shipping_bundle_size')
    op.drop_column('bridge_product_entity', 'shipping_cost_per_bundle')
    # ### end Alembic commands ###
