"""Remove order from media rel

Revision ID: 405541a71a5d
Revises: 06e48eeb19ef
Create Date: 2023-03-13 13:32:47.574369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405541a71a5d'
down_revision = '06e48eeb19ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_media_cat_entity', 'order')
    op.drop_column('bridge_media_prod_entity', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_media_prod_entity', sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bridge_media_cat_entity', sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
