"""Add microseconds to synchronize entity

Revision ID: 4b61799888fe
Revises: 51bf6d93693e
Create Date: 2023-03-29 11:01:19.223335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b61799888fe'
down_revision = '51bf6d93693e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_synchronize_entity', 'sw6_customers_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_product_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_order_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_tax_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_product_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_order_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_category_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_category_sync_date')
    op.drop_column('bridge_synchronize_entity', 'loop_continue')
    op.drop_column('bridge_synchronize_entity', 'dataset_customers_sync_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_customers_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('loop_continue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_category_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_category_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_order_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_product_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_tax_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_order_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_product_sync_date', mysql.DATETIME(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_customers_sync_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
