"""URL for Product

Revision ID: 6db9e5c92f2b
Revises: 89652d6506d5
Create Date: 2023-02-20 08:39:08.534288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db9e5c92f2b'
down_revision = '89652d6506d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_product_entity', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_product_entity', 'url')
    # ### end Alembic commands ###
