"""Unique Constraint for Kombination

Revision ID: 7017ff47fd4b
Revises: 2b28445495de
Create Date: 2023-01-27 08:45:06.358035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7017ff47fd4b'
down_revision = '2b28445495de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_erp_nr_ansnr_aspnr', 'bridge_customer_address_entity', ['erp_nr', 'erp_ansnr', 'erp_aspnr'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_erp_nr_ansnr_aspnr', 'bridge_customer_address_entity', type_='unique')
    # ### end Alembic commands ###
