"""Orders

Revision ID: 893ddf066615
Revises: 649885a855e9
Create Date: 2023-03-16 14:20:29.728162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '893ddf066615'
down_revision = '649885a855e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_order_entity', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('bridge_order_entity', sa.Column('payment_method', sa.String(length=255), nullable=True))
    op.add_column('bridge_order_product_entity', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('bridge_order_product_entity', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('bridge_order_product_entity', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('bridge_order_product_entity', sa.Column('total_price', sa.Float(), nullable=False))
    op.alter_column('bridge_order_product_entity', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('bridge_order_product_entity', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bridge_order_product_entity', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('bridge_order_product_entity', 'order_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('bridge_order_product_entity', 'total_price')
    op.drop_column('bridge_order_product_entity', 'unit_price')
    op.drop_column('bridge_order_product_entity', 'quantity')
    op.drop_column('bridge_order_product_entity', 'id')
    op.drop_column('bridge_order_entity', 'payment_method')
    op.drop_column('bridge_order_entity', 'total_price')
    # ### end Alembic commands ###
