"""Add shipping method

Revision ID: 956ee6149c13
Revises: 95ff2e3f4057
Create Date: 2023-05-24 08:10:36.848432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956ee6149c13'
down_revision = '95ff2e3f4057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_order_entity', sa.Column('shipping_method', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', 'bridge_product_entity', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', type_='foreignkey')
    op.drop_column('bridge_order_entity', 'shipping_method')
    # ### end Alembic commands ###
