"""Add order_number to order entity

Revision ID: 95ff2e3f4057
Revises: ccba055641c9
Create Date: 2023-05-24 07:44:53.068186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ff2e3f4057'
down_revision = 'ccba055641c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_order_entity', sa.Column('order_number', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', 'bridge_product_entity', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', type_='foreignkey')
    op.drop_column('bridge_order_entity', 'order_number')
    # ### end Alembic commands ###
