"""Delete erp_nr from BridgeCustomerEntity

Revision ID: a98b0d60724b
Revises: 7017ff47fd4b
Create Date: 2023-01-31 10:31:19.545573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a98b0d60724b'
down_revision = '7017ff47fd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_customer_entity', 'erp_nr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_customer_entity', sa.Column('erp_nr', mysql.CHAR(length=10), nullable=True))
    # ### end Alembic commands ###
