"""Add erp_nr to BridgeCustomerEntity

Revision ID: ae717ff01ad9
Revises: a98b0d60724b
Create Date: 2023-01-31 10:32:26.093297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae717ff01ad9'
down_revision = 'a98b0d60724b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_customer_entity', sa.Column('erp_nr', sa.CHAR(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_customer_entity', 'erp_nr')
    # ### end Alembic commands ###
