"""Delete erp_ltz_aend field in bridge - obsolete

Revision ID: d1f7185f18b2
Revises: 6e57de3fbf90
Create Date: 2023-04-13 09:29:41.759930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1f7185f18b2'
down_revision = '6e57de3fbf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('api_id', table_name='bridge_customer_entity')
    op.drop_index('erp_nr', table_name='bridge_customer_entity')
    op.create_unique_constraint(op.f('uq_bridge_customer_entity_erp_nr'), 'bridge_customer_entity', ['erp_nr'])
    op.drop_column('bridge_customer_entity', 'erp_ltz_aend')
    op.create_foreign_key(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', 'bridge_product_entity', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bridge_price_entity_product_id_bridge_product_entity'), 'bridge_price_entity', type_='foreignkey')
    op.add_column('bridge_customer_entity', sa.Column('erp_ltz_aend', mysql.DATETIME(), nullable=True))
    op.drop_constraint(op.f('uq_bridge_customer_entity_erp_nr'), 'bridge_customer_entity', type_='unique')
    op.create_index('erp_nr', 'bridge_customer_entity', ['erp_nr'], unique=False)
    op.create_index('api_id', 'bridge_customer_entity', ['api_id'], unique=False)
    # ### end Alembic commands ###
