"""Add microseconds to synchronize entity

Revision ID: e8a3aa4a0389
Revises: 4b61799888fe
Create Date: 2023-03-29 11:01:45.756371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a3aa4a0389'
down_revision = '4b61799888fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_category_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_product_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_customers_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_tax_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('dataset_order_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_category_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_product_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_customers_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('sw6_order_sync_date', sa.DateTime(), nullable=True))
    op.add_column('bridge_synchronize_entity', sa.Column('loop_continue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge_synchronize_entity', 'loop_continue')
    op.drop_column('bridge_synchronize_entity', 'sw6_order_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_customers_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_product_sync_date')
    op.drop_column('bridge_synchronize_entity', 'sw6_category_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_order_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_tax_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_customers_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_product_sync_date')
    op.drop_column('bridge_synchronize_entity', 'dataset_category_sync_date')
    # ### end Alembic commands ###
