"""Fremdschlüssel

Revision ID: ef8cf1e9f7c4
Revises: 8cd045f578a0
Create Date: 2023-06-28 08:38:46.262345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef8cf1e9f7c4'
down_revision = '8cd045f578a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bridge_customer_entity_billing_address_id_bridge_cust_c902', 'bridge_customer_entity', type_='foreignkey')
    op.drop_constraint('fk_bridge_customer_entity_shipping_address_id_bridge_cus_fc1c', 'bridge_customer_entity', type_='foreignkey')
    op.drop_column('bridge_customer_entity', 'shipping_address_id')
    op.drop_column('bridge_customer_entity', 'billing_address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_customer_entity', sa.Column('billing_address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bridge_customer_entity', sa.Column('shipping_address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_bridge_customer_entity_shipping_address_id_bridge_cus_fc1c', 'bridge_customer_entity', 'bridge_customer_address_entity', ['shipping_address_id'], ['id'])
    op.create_foreign_key('fk_bridge_customer_entity_billing_address_id_bridge_cust_c902', 'bridge_customer_entity', 'bridge_customer_address_entity', ['billing_address_id'], ['id'])
    # ### end Alembic commands ###
